import "unknwn.idl";
import "oaidl.idl";
import "ocidl.idl";
import "objidl.idl";
import "strmif.idl";

[object, uuid("9C8550A8-8D53-43B5-8A33-9F4D0283B829")]
interface IAudioAnalyzerFilterCallback : IUnknown
{

}

[object, uuid("77363364-8A9F-45EF-A524-D02C49B3FE38")]
interface IAudioAnalyzerFilter : IUnknown
{
    [propget, id(1), helpstring("Is the analyzer enabled")] HRESULT Enabled([out, retval] VARIANT_BOOL* pVal);
    [propput, id(1), helpstring("Is the analyzer enabled")] HRESULT Enabled([in] VARIANT_BOOL newVal);

    [id(2), helpstring("Register or remove a callback for the events of the filter")]
    HRESULT SetCallback(IAudioAnalyzerFilterCallback* pCallback);
};

[
	uuid("C088C321-CC00-44AC-82F2-BDC6601E6753"), 
    helpstring("Audio Analyzer Filter Type Library"),
	//lcid(0x0409), // EN-US
    version(1.0)
] 
library AudioAnalyzerFilterLib
{
    interface IAudioAnalyzerFilterCallback;
    interface IAudioAnalyzerFilter;

    [uuid("F896EF1A-3FE4-4D22-9B61-1288240FD39F")]
    coclass AudioAnalyzerFilter
    {
        interface IBaseFilter;
        [default] interface IAudioAnalyzerFilter;
    }
};
