//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by graphstudionext.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_DIALOGBAR                   103
#define IDD_BAR_SEEKING                 103
#define IDD_DIALOG_FILTERDETAILS        105
#define IDD_PROPPAGE_WMRESIZER          106
#define IDR_MAINFRAME                   128
#define IDR_graphstudioTYPE             129
#define IDB_BITMAP_LOGO                 130
#define IDR_TOOLBAR1                    131
#define IDD_DIALOG_FILTERS              134
#define IDD_DIALOG_EVENTS               135
#define IDD_DIALOG_TEXTVIEW             136
#define IDD_DIALOG_ASYNCOPEN            137
#define IDD_DIALOG_PROPERTYPAGE         138
#define IDD_DIALOG_ROT                  141
#define IDD_DIALOG_ASYNCOPEN1           142
#define IDD_DIALOG_FILESINK             142
#define IDD_DIALOG_FAVORITES            143
#define IDB_BITMAP_TREE                 144
#define IDR_MENU_FAVORITES              145
#define IDD_DIALOG_NEWGROUP             146
#define IDD_DIALOG_RENDERURL            147
#define IDD_DIALOG_PROGRESS             148
#define IDB_BITMAP_VOLUME_HI            149
#define IDB_BITMAP_VOLUME_LO            150
#define IDD_DIALOG_VOLUMEBAR            150
#define IDB_BITMAP_CLOCK_ACTIVE_HI      151
#define IDB_BITMAP_CLOCK_ACTIVE_LO      152
#define IDB_BITMAP_CLOCK_INACTIVE_HI    153
#define IDB_BITMAP_CLOCK_INACTIVE_LO    154
#define IDD_DIALOG_SEEK                 155
#define IDD_DIALOG_SCHEDULE             156
#define IDD_DIALOG_VCM_DIALOGS          157
#define IDD_DIALOG_VCM                  158
#define IDD_DIALOG_AUDIO_COMPRESS       159
#define IDD_DIALOG_DEC_PERFORMANCE      160
#define IDD_DIALOG_UNREGCONFIRM         161
#define IDD_DIALOG_MERITCHANGE          162
#define IDD_DIALOG_BUFFERNEG            163
#define IDD_DIALOG_WMADECODER           164
#define IDD_DIALOG_CONSTRUCTION         165
#define IDD_DIALOG_FILTERFROMFILE       166
#define IDC_COMBO_CATEGORIES            1001
#define IDC_LIST_FILTERS                1002
#define IDC_COMBO_MERIT                 1003
#define IDC_BUTTON_REGISTER             1004
#define IDC_LIST_DETAILS                1005
#define IDC_CHECK_FAVORITE              1006
#define IDC_BUTTON_PROPERTYPAGE         1007
#define IDC_BUTTON_COPYTEXT             1007
#define IDC_BUTTON3                     1008
#define IDC_BUTTON_UNREGISTER           1008
#define IDC_BUTTON_SAVE                 1008
#define IDC_BUTTON_INSERT               1009
#define IDC_BUTTON_MEDIATYPES           1010
#define IDC_BUTTON_LOCATE               1010
#define IDC_STATIC_TITLE                1011
#define IDC_BUTTON_MERIT                1011
#define IDC_STATIC_SEPARATOR            1012
#define IDC_BUTTON_CLEAR                1013
#define IDC_LIST_EVENTS                 1014
#define IDC_BUTTON2                     1015
#define IDC_BUTTON_COPY                 1015
#define IDC_BUTTON_REFRESH              1015
#define IDC_BUTTON_ABOUT                1015
#define IDC_SLIDER1                     1016
#define IDC_SLIDER_SEEK                 1016
#define IDC_SLIDER_VOLUME               1016
#define IDC_SLIDER_IRATE                1016
#define IDC_STATIC_TIME                 1017
#define IDC_SLIDER_BALANCE              1017
#define IDC_SLIDER_PRATE                1017
#define IDC_BUTTON1                     1018
#define IDC_BUTTON_BROWSE               1018
#define IDC_BUTTON_APPLY                1018
#define IDC_BUTTON_CLOSE                1018
#define IDC_BUTTON_CONFIG               1018
#define IDC_BUTTON_DEF_IRATE            1018
#define IDC_BUTTON_SET                  1018
#define IDC_EDIT_DETAILS                1019
#define IDC_BUTTON_DEF_PRATE            1019
#define IDC_COMBO_REPORTTYPE            1020
#define IDC_RADIO_FILE                  1021
#define IDC_RADIO_URL                   1022
#define IDC_SLIDER_QUALITY              1022
#define IDC_COMBO_FILE                  1023
#define IDC_BUTTON_DEF_QUALITY          1023
#define IDC_COMBO_URL                   1024
#define IDC_SLIDER_WINDOW               1024
#define IDC_TAB1                        1025
#define IDC_TAB_PAGES                   1025
#define IDC_BUTTON_DEF_WINDOW           1025
#define IDC_TITLEBAR                    1027
#define IDC_TITLE                       1028
#define IDC_LIST_GRAPHS                 1029
#define IDC_BUTTON_CONNECT              1030
#define IDC_TREE_FAVORITES              1030
#define IDC_EDIT1                       1031
#define IDC_EDIT_NAME                   1031
#define IDC_EDIT_TIME                   1031
#define IDC_EDIT_PASSES                 1031
#define IDC_EDIT_ORIGINAL               1031
#define IDC_EDIT_LATENCY                1031
#define IDC_EDIT_SRC_TOP                1031
#define IDC_EDIT_DST_TOP                1032
#define IDC_TREE1                       1033
#define IDC_TREE                        1033
#define IDC_PROGRESS_POSITION           1034
#define IDC_CHECK_AUTOSWITCH            1035
#define IDC_STATIC_CAPTION              1037
#define IDC_STATIC_VOLUME               1038
#define IDC_STATIC_BALANCE              1039
#define IDC_RADIO_TIME                  1040
#define IDC_RADIO_FRAME                 1041
#define IDC_CHECK_KEYFRAME              1042
#define IDC_EDIT_FRAME                  1043
#define IDC_STATIC_DURATION             1044
#define IDC_STATIC_POSITION             1045
#define IDC_STATIC_FPS                  1046
#define IDC_LIST_SCHEDULE               1048
#define IDC_BUTTON_ADD                  1049
#define IDC_BUTTON_REMOVE               1050
#define IDC_STATIC_DESC                 1051
#define IDC_STATIC_VERSION              1052
#define IDC_STATIC_IRATE                1053
#define IDC_STATIC_PRATE                1054
#define IDC_STATIC_QUALITY              1055
#define IDC_STATIC_WINDOW               1056
#define IDC_STATIC_VAL_IRATE            1057
#define IDC_STATIC_VAL_PRATE            1058
#define IDC_STATIC_VAL_QUALITY          1059
#define IDC_STATIC_VAL_WINDOW           1060
#define IDC_COMBO_SAMPLERATE            1061
#define IDC_COMBO_CHANNELS              1062
#define IDC_COMBO_BITRATE               1063
#define IDC_STATIC_FORMAT               1064
#define IDC_STATIC_CHANNELS             1065
#define IDC_STATIC_SAMPLERATE           1066
#define IDC_STATIC_BITRATE              1067
#define IDC_COMBO4                      1068
#define IDC_COMBO_FORMAT                1068
#define IDC_COMBO_PRESETS               1068
#define IDC_COMBO_RENDERER              1071
#define IDC_LIST_RESULTS                1072
#define IDC_COMBO_DECODER               1073
#define IDC_SPIN_PASSES                 1074
#define IDC_BUTTON_START                1075
#define IDC_BUTTON_STOP                 1076
#define IDC_STATIC_FILTER               1077
#define IDC_COMBO_RENDERER2             1077
#define IDC_COMBO_TYPE                  1077
#define IDC_COMBO_NEW                   1078
#define IDC_LIST3                       1081
#define IDC_LIST_CAPS                   1081
#define IDC_STATIC_ALIGN                1082
#define IDC_STATIC_BUFFER               1083
#define IDC_STATIC_PREFIX               1084
#define IDC_STATIC_BUFFERS              1085
#define IDC_STATIC_RATE                 1086
#define IDC_STATIC_BYTES                1087
#define IDC_STATIC_URL                  1089
#define IDC_CHECK_HIRES                 1090
#define IDC_EXPLORER1                   1091
#define IDC_EXPLORER2                   1092
#define IDC_SYSLINK1                    1093
#define IDC_MFCLINK_SEARCH_ONLINE       1096
#define IDC_CHECK_UNREGALL              1097
#define IDC_COMBO_CLSID                 1098
#define IDC_EDIT_SRC_LEFT               1100
#define IDC_EDIT_SRC_WIDTH              1101
#define IDC_EDIT_SRC_HEIGHT             1102
#define IDC_EDIT_DST_LEFT               1103
#define IDC_EDIT_DST_WIDTH              1104
#define IDC_EDIT_DST_HEIGHT             1105
#define IDC_CHECK_INTERLACED            1106
#define IDC_RADIO_QUAL_HIGH             1107
#define IDC_RADIO2                      1108
#define IDC_RADIO_QUAL_FAST             1108
#define ID_LIST_MRU_CLEAR               4999
#define ID_LIST_MRU_FILE0               5000
#define ID_AUDIO_SOURCE0                6000
#define ID_VIDEO_SOURCE0                6050
#define ID_AUDIO_RENDERER0              6100
#define ID_VIDEO_RENDERER0              6150
#define ID_INTERNAL_FILTER0             6200
#define ID_FAVORITE_FILTER              6250
#define ID_STREAM_SELECT                6800
#define ID_PREFERRED_VIDEO_RENDERER     8000
#define ID_COMPATIBLE_FILTER            9000
#define ID_Menu                         32771
#define ID_FILE_RENDERURL               32772
#define ID_FILE_RENDERDVD               32773
#define ID_FILE_RENDERCAPTURE           32774
#define ID_FILE_CONNECTTOREMOTEGRAPH    32775
#define ID_FILE_DISCONNECTFROMREMOTEGRAPH 32776
#define ID_BUTTON_PLAY                  32777
#define ID_BUTTON_PAUSE                 32778
#define ID_BUTTON_STOP                  32779
#define ID_FILE_RENDERFILE              32780
#define ID_GRAPH_INSERTFILTER           32781
#define ID_VIEW_GRAPHEVENTS             32782
#define ID_VIEW_SEEKINGBAR              32783
#define ID_VIEW_TEXTINFORMATION         32784
#define ID_GRAPH_INSERTFILESOURCE       32785
#define ID_PROPERTYPAGE                 32786
#define ID_PIN_RENDER                   32787
#define ID_GRAPH_MAKEGRAPHSCREENSHOT    32788
#define ID_VIEW_50                      32794
#define ID_VIEW_75                      32795
#define ID_VIEW_100                     32796
#define ID_VIEW_150                     32797
#define ID_VIEW_200                     32798
#define ID_BUTTON_ADD_FILTERS           32799
#define ID_GRAPH_INSERTFILEWRITER       32805
#define ID_GRAPH_INSERTVIDEORENDERER    32806
#define ID_GRAPH_INSERTAUDIORENDERER    32807
#define ID_FILE_ADDMEDIAFILE            32808
#define ID_FILTERS_DOUBLESELECTEDFILTERS 32809
#define ID_VIEW_DECREASEZOOMLEVEL       32812
#define ID_VIEW_INCREASEZOOMLEVEL       32813
#define ID_FILTERS_MANAGEFAVORITES      32818
#define ID_MENU_CREATEGROUP             32819
#define ID_MENU_REMOVEGROUP             32820
#define ID_MENU_REMOVEFILTER            32821
#define ID_OPTIONS_AUTOMATICRESTART     32822
#define ID_AUTOMATICRESTART_DISABLED    32823
#define ID_AUTOMATICRESTART_EVERYHOUR   32824
#define ID_AUTOMATICRESTART_EVERYTWOHOURS 32825
#define ID_AUTOMATICRESTART_EVERY4HOURS 32826
#define ID_AUTOMATICRESTART_AT04        32827
#define ID_AUTORESTART                  32828
#define ID_AUTORESTART_DISABLED         32829
#define ID_FILE_OPENFROMXML             32830
#define ID_FILE_SAVEASXML               32831
#define ID_OPTIONS_DISPLAYFILTERNAME    32832
#define ID_OPTIONS_DISPLAYASFILENAME    32833
#define ID_BUTTON32834                  32834
#define ID_BUTTON_DIRECT                32834
#define ID_OPTIONS_DIRECTCONNECTMODE    32835
#define IDC_OPTIONS_DIRECT              32836
#define ID_OPTIONS_DIRECT               32837
#define ID_BUTTON_STEP                  32838
#define ID_BUTTON_PLAYPAUSE             32841
#define ID_BUTTON_REFRESH               32843
#define ID_GRAPH_REFRESHGRAPH           32844
#define ID_VIEW_PROGRESSVIEW            32845
#define ID_PIN_NULL_STREAM              32847
#define ID_PIN_DUMP_STREAM              32848
#define ID_GRAPH_USECLOCK               32849
#define ID_BUTTON32850                  32850
#define ID_BUTTON_SEEK                  32851
#define ID_AUTOMATICRESTART_SCHEDULE    32852
#define ID_OPTIONS_PREFERREDVIDEORENDERER 32853
#define ID_VIEW_DECODERPERFORMANCE      32854
#define ID_PIN_FILE_WRITER              32855
#define ID_OPTIONS_USEEXACTMATCHTOFINDCOMPATIBLEFILTERS 32856
#define ID_OPTIONS_EXACTMATCH           32857
#define ID_OPTIONS_ABORTRENDERAFTER10SECONDS 32858
#define ID_OPTIONS_ABORTRENDER          32859
#define ID_VIEW_GRAPHCONSTRUCTIONREPORT 32860
#define ID_DELETE_FILTER                32861
#define ID_GRAPH_INSERTAUDIOSOURCE      32862
#define ID_GRAPH_INSERTVIDEOSOURCE      32863
#define ID_GRAPH_INSERTFILTERFROMFILE   32864
#define ID_OPTIONS_USEMEDIAINFO         32865
#define ID_GRAPH_INSERTINTERNALFILTER   32866

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32867
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
